#Problem 2: Even Fibonacci numbers

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibSum(targetNum):
	term1 = 0
	term2 = 1
	fibSeries = []
	nextTerm = 0
	Sum = 0
	
	while nextTerm <= targetNum:
		fibSeries.append(nextTerm)
		term1 = term2
		term2 = nextTerm
		nextTerm = term1 + term2

	print(fibSeries)
	
	for number in fibSeries:
		if number % 2 == 0:
			Sum += number
	print(Sum)
	
fibSum(4000000)	
